#!/usr/bin/env python3
"""Re-quote all frontmatter string values for TrustMRR-generated case files.

Target: every <slug>.md in src/content/cases whose slug also exists in
pipeline/trustmrr_cache (i.e. generated by gen_trustmrr.py). The body (LLM
prose) is preserved untouched; only the YAML frontmatter block is re-emitted
with every scalar value double-quoted so YAML can never coerce a number/bool
into a non-string and trip the Zod z.string() schema.

Quoting is universally safe for this schema: every field is either a string or
a fixed enum literal, and Zod enums accept quoted string literals.
"""
import os
import re

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
CACHE_DIR = os.path.join(ROOT, "pipeline", "trustmrr_cache")
CASES_DIR = os.path.join(ROOT, "src", "content", "cases")


def yq(v):
    s = "" if v is None else str(v)
    s = s.replace("\\", "\\\\").replace('"', '\\"').replace("\n", " ").replace("\r", " ")
    return '"' + s + '"'


def fix_file(path):
    with open(path, encoding="utf-8") as f:
        text = f.read()
    if not text.startswith("---\n"):
        return False
    # split frontmatter (first two --- lines) and body
    m = re.match(r"^---\n(.*?)\n---\n?(.*)$", text, re.S)
    if not m:
        return False
    fm_raw = m.group(1)
    body = m.group(2)
    out_lines = []
    changed = False
    for line in fm_raw.split("\n"):
        if not line.strip():
            out_lines.append(line)
            continue
        # key: value  (key may contain CJK, no colon)
        mm = re.match(r"^([^:]+):\s?(.*)$", line)
        if not mm:
            out_lines.append(line)
            continue
        key = mm.group(1)
        val = mm.group(2)
        # skip already-quoted to keep idempotent & avoid double-quoting
        if val.startswith('"') and val.endswith('"') and len(val) >= 2:
            out_lines.append(line)
            continue
        if val == "":
            out_lines.append(f"{key}: \"\"")
            changed = True
            continue
        out_lines.append(f"{key}: {yq(val)}")
        changed = True
    if not changed:
        return False
    new_text = "---\n" + "\n".join(out_lines) + "\n---\n" + body
    with open(path, "w", encoding="utf-8") as f:
        f.write(new_text)
    return True


def main():
    cache_slugs = {f[:-3] for f in os.listdir(CACHE_DIR) if f.endswith(".md")}
    fixed = 0
    skipped = 0
    for fn in os.listdir(CASES_DIR):
        if not fn.endswith(".md"):
            continue
        slug = fn[:-3]
        if slug not in cache_slugs:
            skipped += 1
            continue
        if fix_file(os.path.join(CASES_DIR, fn)):
            fixed += 1
    print(f"fixed={fixed} skipped(non-trustmrr)={skipped}")


if __name__ == "__main__":
    main()
